### ISSUE TITLE
Pass Parent module name to included xml files for publishing sensor reading

### ISSUE THREAD

**Issue by SRai22** [MRPT/mvsim#18]
It would be very helpful if there was example on how to pass the vehicle name variable to included sensor xml files for better sensor publisher name.

**Comment by jlblancoc** [comment]
It was actually not possible to do that until now, but after the latest commit it is! See the new tutorial files in 05c26a4d0ffeeed49b291a22d508a136f56928ac


Closed via 05c26a4d0ffeeed49b291a22d508a136f56928ac
