### ISSUE TITLE
Box2d assertion fail causing coredump

### ISSUE THREAD

**Issue by SRai22** [MRPT/mvsim#25]
When launching the simulation world, encountering this error: 

"mvsim: /tmp/ws/src/externals/box2d/src/collision/b2_polygon_shape.cpp:156: void b2PolygonShape::Set(const b2Vec2*, int32): Assertion `false' failed." 

Would I need to upgrade box2d from 2.4.1 or continue using the same. 

Thanks

**Comment by SRai22** [comment]
Thanks for the update :+1:

**Comment by jlblancoc** [comment]
Fixed via 16485676aa97073a65cb11bf2e0bbb3c7497f021

One of the DAE models (after rotating to make +Z up) had its minimum Z <0, so those vertices were not accounted for while determining the bbox from the mesh using the (recently-added) Z-based filter for it (`block_z_min` and `block_z_max`)

Cheers!
