### ISSUE TITLE
multiple robots simulations in ros2

### ISSUE THREAD

**Issue by francocipollone** [MRPT/mvsim#29]
Hi there, great job on the simulator. Having something lightweight for multiple robot simulations is a great deal. :rocket: 

One question related to the ros2 support. I noticed that there are no examples of using multiple robots in ros2.

Is there pending stuff to be tackled in order to provide full support here to ros2?

**Comment by jlblancoc** [comment]
Hi!

Sure, it works with multiple robots on ROS 1 and ROS 2 alike.

Just we probably overlooked adding the examples for ROS 2. I [just added one example](46f000ff00a8b384539d4ab81d3eef357054c437).

**Comment by francocipollone** [comment]
Oh, I should've digged a bit more, thanks for the quick action :rocket:
