### ISSUE TITLE
About LIDAR Triangularity

### ISSUE THREAD

**Issue by omerfarukadastec** [MRPT/mvsim#34]
Hi,

I am using MVSim to see and analyze the effectiveness of the LIDAR positions. But the point that I am curious about it is the working system of LIDAR in MVSim. I am expecting a circular output but especially in further distances, LIDAR outputs are seen as triangular. I am using OUSTER LIDAR in simulation. Can I change the triangularity to circularity or is it impossible to change? Also why the LIDAR output is seen triangular in MVSim? I would be very pleased if you are answer. Thanks in advance. There are some pictures of outputs that I am getting in below.

![Screenshot from 2023-10-06 13-20-13](https://github.com/MRPT/mvsim/assets/104622368/0c7e230d-a5c0-4478-83b7-7b9ba7097346)

![Screenshot from 2023-10-06 13-20-33](https://github.com/MRPT/mvsim/assets/104622368/06e02754-36f1-4b73-a784-f449cfd608dc)

**Comment by jlblancoc** [comment]
The way 3D Lidar simulation works deserves a paper to explain it in detail... :-) 
But in short: the 360 deg FOV is split into N views from a "fake" RGBD-like camera, then the data is converted to match the "ring-like" sampling of space done by lidars. 

By default, N=3... hence the triangles. But we set default parameters such that it was barely noticeable in our tests, so I'm curious about your case. 
Please, would you provide: 
- Your GPU details?
- A ZIP with your test world + vehicle + sensor definition? Don't include any textures, etc. just the most simple case that shows these artifacts. 

You can also experiment increasing the parameters `vert_resolution_factor` and maybe also `horz_resolution_factor` while including your lidar sensor in the world model. Refer to the list of parameters [here](https://mvsimulator.readthedocs.io/en/latest/sensors.html#sensor-definition-and-common-parameters). Set them to 1.5, 2.0, 2.5, 3.0, etc. to see if it makes any improvement.

**Comment by jlblancoc** [comment]
After revisiting this, you are right: HELIOS and VLP-16 lidars seem circular, but Ouster looks like a triangle in my system too (!). 
I'll dig into it...

**Comment by jlblancoc** [comment]
Fixed in the new release ;-) 

https://www.linkedin.com/posts/jose-luis-blanco-claraco-7511b712_ros-ros2-simulator-activity-7116191274721812481-TnDZ
