### ISSUE TITLE
Cannot see output pointcloud in RViz 

### ISSUE THREAD

**Issue by omerfarukadastec** [MRPT/mvsim#41]
Hi,

I am encountering an error that causes me to not be able to see pointclouds on RViz. I can see pointclouds on the GUI, MVSim is working, but on the terminal I get the following error for each LIDAR.

![Screenshot from 2024-02-29 13-22-18](https://github.com/MRPT/mvsim/assets/104622368/4616140c-6820-4174-8693-91d75eb1a073)

What should I do?

MRPT version: 2.11.5

**Comment by omerfarukadastec** [comment]
Hi,

Thanks for the answer & suggestion. I updated MRPT to 2.11.10 from 2.11.5. I updated with building from source because in ppa installation, apt is installing the 2.11.6. I also removed the old one. After installation, I am still getting the same error. 

I thought it is about that there are no "toROS" function for CPointsMapXYZIRT. I defined macros for HAVE_POINT_XYZIRT for ROS1 side but in this situation, MVSim cannot be build successfully, it gives the error "error: call of overloaded ‘toROS(const mrpt::maps::CPointsMapXYZIRT&, std_msgs::Header&, sensor_msgs::PointCloud2&)’ is ambiguous".

Is it really about that there are no "toROS" function for CPointsMapXYZIRT? Or did I something wrong?

Thanks in advance.

**Comment by jlblancoc** [comment]
What about installing mvsim (and hence mrpt automatically) via apt from the ros-noetic-mvsim package??

**Comment by jlblancoc** [comment]
I can confirm it's still an issue on the latest version of mvsim+mrpt for ROS 1 only. I'll investigate it.

**Comment by omerfarukadastec** [comment]
Thanks, it works very well. Thanks for your considerations & help.
