### ISSUE TITLE
Connecting my own navigation stack with mvsim simulated robot.

### ISSUE THREAD

**Issue by afrozsevenrobotics** [MRPT/mvsim#44]
how can I run external amcl stack for simulated robot

**Comment by jlblancoc** [comment]
Hi, 

I think you need to disable [this ROS param](https://github.com/MRPT/mvsim/blob/develop/mvsim_tutorial/mvsim_ros2_params.yaml#L5) to **false**: 

    do_fake_localization: true     # publish tf odom -> base_link

It's true by default to help beginners to launch mvsim easily without a nav stack.

**Comment by jlblancoc** [comment]
PS: Most launch files have this exposed as a launch argument also named `do_fake_localization`, e.g. https://github.com/MRPT/mvsim/blob/develop/mvsim_tutorial/demo_turtlebot_world.launch.py#L27
 
so it should be enough to do: 

    ros2 launch mvsim demo_turtlebot_world.launch.py do_fake_localization:=False

**Comment by jlblancoc** [comment]
Closing, reopen if needed!
