### ISSUE TITLE
Topics and frame ids for compatibility with Nav2

### ISSUE THREAD

**Issue by finani** [MRPT/mvsim#49]
As I mentioned about the rule of Nav2 [(PR)](https://github.com/ros-navigation/navigation2/pull/4594) before, topics are separated by namespace and each topic should have the same frame id.
I thought this rule is only for tf [(PR)](https://github.com/MRPT/mvsim/pull/45), but every topics including sensors should follow this.

I want to add compatibility with Nav2 to mvsim, but I worry about I will break the policy and projects using mvsim.
If there is any rule to follow, I will consider to add additional parameter.

I think there are three options.
a) Make every frame id of each topic the same. (radical)
b) Add parameter to control frame ids. (safe)
c) This changes are not considered in mvsim. (abort)

I will follow the decision.

### before (now)

- r1

| topic name | frame id |
| ----------- | -------- |
| cam1           | cam1      |

- r1, r2

| topic name | frame id |
| ----------- | -------- |
| r1/cam1       | r1/cam1  |
| r2/cam1       | r2/cam1 |

### after (compatible with Nav2)

- r1

| topic name | frame id |
| ----------- | -------- |
| cam1           | cam1      |

- r1, r2

| topic name | frame id |
| ----------- | -------- |
| r1/cam1       | cam1      |
| r2/cam1       | cam1     |

**Comment by jlblancoc** [comment]
So, what I see is that topics are ok: in Nav2 they use as prefix the robot name and mvsim does too, and I think it all makes sense. 

On /tf: what I understand in Steve's answer in https://github.com/ros-navigation/navigation2/pull/4594 is that each robot listen to the tf **topic** ``tf`` so it becomes ``/tf`` or ``/r1/tf``, etc. depending on the case, right? 

What I don't understand is how to avoid collisions between **frame_id**s (not the /tf topics themselves). 

Maybe the point is that multi-robot systems are expected **not** to share /tf, right?? cc: @SteveMacenski  :pray: 

If the answer is yes, ok, let's follow the same convention here, and we'll fix tutorials, and examples,etc. in mvsim.

**Comment by SteveMacenski** [comment]
> Maybe the point is that multi-robot systems are expected not to share /tf, right?? cc: @SteveMacenski 🙏

For that setup, yea. You don't need to avoid collisions when there are no collisions

**Comment by jlblancoc** [comment]
Alright, @SteveMacenski , thanks, it makes sense. 

@finani Then, go on and feel free of PR for making things compatible with multi-robot Nav2. :+1:

**Comment by finani** [comment]
Thank you all.

Yes, Exactly I worried about frame id collisions.
Because I was already using the entire tf tree for monitoring, and tf tree works only using frame ids.
But, after splitting by namespace, even rviz, It has no problem. (Thanks Steve)

Thank you again.
I will go update this feature.

**Comment by finani** [comment]
https://github.com/MRPT/mvsim/pull/51 is merged
Close this issue.
