### ISSUE TITLE
"hand of god" dynamics support

### ISSUE THREAD

**Issue by vinnnyr** [MRPT/mvsim#56]
Hello,

What is the best way to implement a "hand of god" dynamics (such that we can force a certain position, velocity of the robot rather through pub/sub rather than use setpoints and controllers)?

Vinny

**Comment by jlblancoc** [comment]
Hi! At present, that is only offered as a Service via ZMQ (not ROS yet...). 

But it's pretty straightforward, see this example: 
https://github.com/MRPT/mvsim/blob/develop/examples_python/move-object-example.py

In fact, that code already does exactly that: moving the robot "r1" around. 

Setting both pose & velocity (twist) was supposed to be doable via this similar service: 
 https://github.com/MRPT/mvsim/blob/develop/modules/msgs/proto/SrvSetPoseTwist.proto

but it seems I never implemented it (!). If you are interested, it should be easy to add it here: 

https://github.com/MRPT/mvsim/blob/a263ea724fed7955ead4ee5dbeb98cd282f51dfd/modules/simulator/src/World_services.cpp#L184-L199

and defining the equivalent of srv_set_pose() for pose & twist.

**Comment by vinnnyr** [comment]
Thanks! that is helpful. Would this service be OK to implement hand of god control of the simulated robot at a high rate, say 20hz? Or is it better to create a vehicle dynamic type that implements this?

For context, I have a decent model of the dynamics of my vehicle, so I would like to use that instead of the physics based control MVSIM has.

**Comment by vinnnyr** [comment]
I guess the example you provided shows moving the object at 100hz, so maybe I should try that first! 
https://github.com/MRPT/mvsim/blob/develop/examples_python/move-object-example.py

**Comment by jlblancoc** [comment]
Closing as I guess that solved the doubt. Reopen if needed!
